In [1]:
import numpy as np
import pandas as pd

## Création d'un DataFrame

In [2]:
age = pd.Series([30, 20, 50], index=['alice', 'bob', 'julie'])

In [3]:
height = pd.Series([150, 170, 168], index=['alice', 'marc', 'julie'])

- `Pandas` fait automatiquement l'alignement des index

In [4]:
stat = pd.DataFrame({'age': age, 'height': height})

In [5]:
stat

        age  height
alice  30.0   150.0
bob    20.0     NaN
julie  50.0   168.0
marc    NaN   170.0

- Broadcasting d'une valeur de colonne sur toutes les lignes

In [6]:
stat = pd.DataFrame({'age': age, 'height': height, 'city': 'Nice'})
print(stat)

        age  height  city
alice  30.0   150.0  Nice
bob    20.0     NaN  Nice
julie  50.0   168.0  Nice
marc    NaN   170.0  Nice

In [7]:
print(stat.index)

Index(['alice', 'bob', 'julie', 'marc'], dtype='str')

In [8]:
print(stat.columns)

Index(['age', 'height', 'city'], dtype='str')

In [9]:
print(stat.values)

[[30.0 150.0 'Nice']
 [20.0 nan 'Nice']
 [50.0 168.0 'Nice']
 [nan 170.0 'Nice']]

- Accéder aux données d'un DataFrame

In [10]:
a = stat.loc['alice', 'age']

In [11]:
type(a)

numpy.float64

In [12]:
print(a)

30.0

In [13]:
c = stat.loc[:, 'age']
m = c.mean()
print(f"L'âge moyen est de {m:.1f} ans.")

L'âge moyen est de 33.3 ans.

In [14]:
type(c)

pandas.Series

In [15]:
type(m)

numpy.float64

In [16]:
a = np.random.randint(1, 20, 9).reshape(3, 3)
p = pd.DataFrame(a, index=['a', 'b', 'c'], columns=['x', 'y', 'z'])

In [17]:
print(a)

[[12  6  5]
 [13 11  4]
 [ 5 18  4]]

In [18]:
p

    x   y  z
a  12   6  5
b  13  11  4
c   5  18  4

In [19]:
print(p)

    x   y  z
a  12   6  5
b  13  11  4
c   5  18  4

In [20]:
prenoms = ['liz', 'bob', 'bill', 'eve']

In [21]:
age = pd.Series([25, 30, 35, 40], index=prenoms)

In [22]:
taille = pd.Series([160, 175, 170, 180], index=prenoms)

In [23]:
sexe = pd.Series(list("fhhf"), index=prenoms)

In [24]:
df = pd.DataFrame(
    {
        'age': age,
        'taille': taille,
        'sexe': sexe
    },
)

In [25]:
df

      age  taille sexe
liz    25     160    f
bob    30     175    h
bill   35     170    h
eve    40     180    f

In [26]:
df.index

Index(['liz', 'bob', 'bill', 'eve'], dtype='str')

In [27]:
df.columns

Index(['age', 'taille', 'sexe'], dtype='str')

In [28]:
df.values

array([[25, 160, 'f'],
       [30, 175, 'h'],
       [35, 170, 'h'],
       [40, 180, 'f']], dtype=object)

In [29]:
df.head(2)

     age  taille sexe
liz   25     160    f
bob   30     175    h

In [30]:
df.tail(2)

      age  taille sexe
bill   35     170    h
eve    40     180    f

In [31]:
df.describe()

             age      taille
count   4.000000    4.000000
mean   32.500000  171.250000
std     6.454972    8.539126
min    25.000000  160.000000
25%    28.750000  167.500000
50%    32.500000  172.500000
75%    36.250000  176.250000
max    40.000000  180.000000

### Indexation de ligne

In [32]:
df.loc['liz']

age        25
taille    160
sexe        f
Name: liz, dtype: object

### Indexation de cellule ou d'observation

In [33]:
print(df.loc['liz', 'age'])

25

### Indexation d'un sous ensemble de DataFrame

In [34]:
df.loc[:, 'taille']

liz     160
bob     175
bill    170
eve     180
Name: taille, dtype: int64

### Application d'un masque et broadcasting

In [35]:
df.loc[df.loc[:, 'age']<32]

     age  taille sexe
liz   25     160    f
bob   30     175    h

### Transformation d'un index ligne en index de colonne

In [36]:
df = df.reset_index()
df

  index  age  taille sexe
0   liz   25     160    f
1   bob   30     175    h
2  bill   35     170    h
3   eve   40     180    f

### Renommer des index de colonne

In [37]:
df = df.rename(columns={'index': 'prenom'})
df

  prenom  age  taille sexe
0    liz   25     160    f
1    bob   30     175    h
2   bill   35     170    h
3    eve   40     180    f

### Redéfinir un index de colonne en tant qu'index de ligne

In [38]:
df = df.set_index('age')
df

    prenom  taille sexe
age
25     liz     160    f
30     bob     175    h
35    bill     170    h
40     eve     180    f

## Approche moderne

In [39]:
df = pd.DataFrame(
    {
        'age': age,
        'taille': taille,
        'sexe': sexe
    },
)

In [40]:
df

      age  taille sexe
liz    25     160    f
bob    30     175    h
bill   35     170    h
eve    40     180    f

In [41]:
df = (
    df.reset_index()
    .rename(columns={'index':'prenoms'})
    .set_index('age')
)

In [42]:
df

    prenoms  taille sexe
age
25      liz     160    f
30      bob     175    h
35     bill     170    h
40      eve     180    f

## Résolution d'alignement d'index

In [43]:
df1 = pd.DataFrame(np.ones((2, 2), dtype=np.int8),
                   index=list('ab'),
                   columns=list('xy')
                   )

In [44]:
df1

   x  y
a  1  1
b  1  1

In [45]:
df2 = pd.DataFrame(np.ones((2, 2), dtype=np.int8),
                   index=list('ac'),
                   columns=list('xz')
                   )

In [46]:
df2

   x  z
a  1  1
c  1  1

In [47]:
df1 + df2

     x   y   z
a  2.0 NaN NaN
b  NaN NaN NaN
c  NaN NaN NaN

- `fill_value` ne fonctionne que s'il manque une valeur à gauche ou à droite (pas si les deux sont absents)

In [48]:
df1.add(df2, fill_value=0)

     x    y    z
a  2.0  1.0  1.0
b  1.0  1.0  NaN
c  1.0  NaN  1.0

In [49]:
df = df1.add(df2, fill_value=0)
df

     x    y    z
a  2.0  1.0  1.0
b  1.0  1.0  NaN
c  1.0  NaN  1.0

- Remplacer les valeur `NaN` par une autre valeur

In [50]:
df.fillna(-1)

     x    y    z
a  2.0  1.0  1.0
b  1.0  1.0 -1.0
c  1.0 -1.0  1.0

- Retirer les lignes contenant des valeurs `NaN`

In [51]:
df.dropna()

     x    y    z
a  2.0  1.0  1.0

## Importation et exportation de données

### Exportation

In [52]:
p

    x   y  z
a  12   6  5
b  13  11  4
c   5  18  4

In [53]:
p.to_csv('data/data.csv')

In [54]:
!cat data/data.csv

,x,y,z
a,12,6,5
b,13,11,4
c,5,18,4

In [55]:
p.to_json('data/data.json')

In [56]:
!cat data/data.json

{"x":{"a":12,"b":13,"c":5},"y":{"a":6,"b":11,"c":18},"z":{"a":5,"b":4,"c":4}}

### Importation

In [57]:
new_p = pd.read_json('data/data.json')
new_p

    x   y  z
a  12   6  5
b  13  11  4
c   5  18  4

In [58]:
new_p = pd.read_csv('data/data.csv')
new_p

  Unnamed: 0   x   y  z
0          a  12   6  5
1          b  13  11  4
2          c   5  18  4

## Manipulation d'une DataFrame

In [59]:
names = ['alice', 'bob', 'marc', 'bill', 'sonia']

age = pd.Series([12, 13, 16, 11, 16], index=names)
height = pd.Series([130, 140, 176, 120, 165], index=names)
sex = pd.Series(list('fmmmf'), index=names)

p = pd.DataFrame({'age': age, 'height': height, 'sex': sex})
print(p)

       age  height sex
alice   12     130   f
bob     13     140   m
marc    16     176   m
bill    11     120   m
sonia   16     165   f

In [60]:
import seaborn as sns

tips = sns.load_dataset('tips')

In [61]:
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [62]:
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [63]:
tips.tail()

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [64]:
tips.index

RangeIndex(start=0, stop=244, step=1)

In [65]:
p.index

Index(['alice', 'bob', 'marc', 'bill', 'sonia'], dtype='str')

In [66]:
tips.values

array([[16.99, 1.01, 'Female', ..., 'Sun', 'Dinner', 2],
       [10.34, 1.66, 'Male', ..., 'Sun', 'Dinner', 3],
       [21.01, 3.5, 'Male', ..., 'Sun', 'Dinner', 3],
       ...,
       [22.67, 2.0, 'Male', ..., 'Sat', 'Dinner', 2],
       [17.82, 1.75, 'Male', ..., 'Sat', 'Dinner', 2],
       [18.78, 3.0, 'Female', ..., 'Thur', 'Dinner', 2]],
      shape=(244, 7), dtype=object)

In [67]:
p.values

array([[12, 130, 'f'],
       [13, 140, 'm'],
       [16, 176, 'm'],
       [11, 120, 'm'],
       [16, 165, 'f']], dtype=object)

In [68]:
tips.keys()

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='str')

In [69]:
p.keys()

Index(['age', 'height', 'sex'], dtype='str')

In [70]:
tips.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='str')

In [71]:
p.columns

Index(['age', 'height', 'sex'], dtype='str')

In [72]:
tips.items()

In [73]:
p.items()

In [74]:
tips.transpose()

,0,1,2,3,4,5,6,7,8,9,...,234,235,236,237,238,239,240,241,242,243
total_bill,16.99,10.34,21.01,23.68,24.59,25.29,8.77,26.88,15.04,14.78,...,15.53,10.07,12.6,32.83,35.83,29.03,27.18,22.67,17.82,18.78
tip,1.01,1.66,3.5,3.31,3.61,4.71,2.0,3.12,1.96,3.23,...,3.0,1.25,1.0,1.17,4.67,5.92,2.0,2.0,1.75,3.0
sex,Female,Male,Male,Male,Female,Male,Male,Male,Male,Male,...,Male,Male,Male,Male,Female,Male,Female,Male,Male,Female
smoker,No,No,No,No,No,No,No,No,No,No,...,Yes,No,Yes,Yes,No,No,Yes,Yes,No,No
day,Sun,Sun,Sun,Sun,Sun,Sun,Sun,Sun,Sun,Sun,...,Sat,Sat,Sat,Sat,Sat,Sat,Sat,Sat,Sat,Thur
time,Dinner,Dinner,Dinner,Dinner,Dinner,Dinner,Dinner,Dinner,Dinner,Dinner,...,Dinner,Dinner,Dinner,Dinner,Dinner,Dinner,Dinner,Dinner,Dinner,Dinner
size,2,3,3,2,4,4,2,4,2,2,...,2,2,2,2,3,3,2,2,2,2

In [75]:
p.T

       alice  bob marc bill sonia
age       12   13   16   11    16
height   130  140  176  120   165
sex        f    m    m    m     f

- Obtenir les premières statistiques avec `describe()` sur des types numériques

In [76]:
tips.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [77]:
p.describe()

             age      height
count   5.000000    5.000000
mean   13.600000  146.200000
std     2.302173   23.605084
min    11.000000  120.000000
25%    12.000000  130.000000
50%    13.000000  140.000000
75%    16.000000  165.000000
max    16.000000  176.000000

- Obtenir des statistiques sur des types numériques et de chaînes de caractères

In [78]:
tips.describe(include='all')

        total_bill         tip   sex smoker  day    time        size
count   244.000000  244.000000   244    244  244     244  244.000000
unique         NaN         NaN     2      2    4       2         NaN
top            NaN         NaN  Male     No  Sat  Dinner         NaN
freq           NaN         NaN   157    151   87     176         NaN
mean     19.785943    2.998279   NaN    NaN  NaN     NaN    2.569672
std       8.902412    1.383638   NaN    NaN  NaN     NaN    0.951100
min       3.070000    1.000000   NaN    NaN  NaN     NaN    1.000000
25%      13.347500    2.000000   NaN    NaN  NaN     NaN    2.000000
50%      17.795000    2.900000   NaN    NaN  NaN     NaN    2.000000
75%      24.127500    3.562500   NaN    NaN  NaN     NaN    3.000000
max      50.810000   10.000000   NaN    NaN  NaN     NaN    6.000000

In [79]:
p.describe(include='all')

              age      height  sex
count    5.000000    5.000000    5
unique        NaN         NaN    2
top           NaN         NaN    m
freq          NaN         NaN    3
mean    13.600000  146.200000  NaN
std      2.302173   23.605084  NaN
min     11.000000  120.000000  NaN
25%     12.000000  130.000000  NaN
50%     13.000000  140.000000  NaN
75%     16.000000  165.000000  NaN
max     16.000000  176.000000  NaN

- Requêtes sur une DataFrame

In [80]:
p

       age  height sex
alice   12     130   f
bob     13     140   m
marc    16     176   m
bill    11     120   m
sonia   16     165   f

In [81]:
p.loc['sonia']

age        16
height    165
sex         f
Name: sonia, dtype: object

In [82]:
print(p.loc['sonia', 'age'])

16

In [83]:
p.loc[:, 'sex'] == 'f'

alice     True
bob      False
marc     False
bill     False
sonia     True
Name: sex, dtype: bool

In [84]:
p.loc[p.loc[:, 'sex'] == 'f', :]

       age  height sex
alice   12     130   f
sonia   16     165   f

In [85]:
p.loc[(p.loc[:, 'sex'] == 'f') & (p.loc[:, 'age'] > 14), :]

       age  height sex
sonia   16     165   f

In [86]:
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [87]:
addition_f = tips.loc[tips.loc[:, 'sex'] == 'Female', 'total_bill'].mean()
print(f"Addition moyenne des femmes : {addition_f:.2f}€")

Addition moyenne des femmes : 18.06€

In [88]:
addition_h = tips.loc[tips.loc[:, 'sex'] == 'Male', 'total_bill'].mean()
print(f"Addition moyenne des hommes : {addition_h:.2f}€")

Addition moyenne des hommes : 20.74€

In [89]:
pourboire_f = tips.loc[tips.loc[:, 'sex'] == 'Female', 'tip'].mean()
print(pourboire_f)

2.8334482758620685

In [90]:
pourboire_h = tips.loc[tips.loc[:, 'sex'] == 'Male', 'tip'].mean()
print(pourboire_h)

3.0896178343949043

In [91]:

print(f"Les femmes laissent {pourboire_f/addition_f:.2%} de pourboire")
print(f"Les hommes laissent {pourboire_h/addition_h:.2%} de pourboire")

Les femmes laissent 15.69% de pourboire
Les hommes laissent 14.89% de pourboire

In [92]:
p

       age  height sex
alice   12     130   f
bob     13     140   m
marc    16     176   m
bill    11     120   m
sonia   16     165   f

In [93]:
p['mean'] = 1
p

       age  height sex  mean
alice   12     130   f     1
bob     13     140   m     1
marc    16     176   m     1
bill    11     120   m     1
sonia   16     165   f     1

In [94]:
p.loc[:, 'mean']

alice    1
bob      1
marc     1
bill     1
sonia    1
Name: mean, dtype: int64

### `df.drop()`

In [95]:
pp = p.drop(columns='mean')
pp

       age  height sex
alice   12     130   f
bob     13     140   m
marc    16     176   m
bill    11     120   m
sonia   16     165   f

In [96]:
p.drop(columns='mean', inplace=True)
print(p)

       age  height sex
alice   12     130   f
bob     13     140   m
marc    16     176   m
bill    11     120   m
sonia   16     165   f

## Les `ufunc` avec pandas

In [97]:
d = pd.DataFrame(
    np.random.randint(1, 10, 9).reshape(3, 3),
    columns=list('abc')
)

print(d)

   a  b  c
0  7  3  9
1  4  1  7
2  8  6  2

In [98]:
np.log(d)

          a         b         c
0  1.945910  1.098612  2.197225
1  1.386294  0.000000  1.945910
2  2.079442  1.791759  0.693147

- Si l’on a besoin d’alignement de labels, les ufunc de numpy ne vont pas faire ce à quoi on s’attend. Elles vont faire les opérations sur les tableaux numpy sans prendre en compte les labels. Pour avoir un alignement des labels, il faut utiliser les ufunc de pandas.

In [99]:
s1 = pd.Series([10, 20, 30], index=list('abc'))

print(s1)

a    10
b    20
c    30
dtype: int64

In [100]:
s2 = pd.Series([12, 22, 32], index=list('acd'))

print(s2)

a    12
c    22
d    32
dtype: int64

In [101]:
np.add(s1, s2)

a    22.0
b     NaN
c    52.0
d     NaN
dtype: float64

In [102]:
s1.add(s2)

a    22.0
b     NaN
c    52.0
d     NaN
dtype: float64

In [103]:
s1.add(s2, fill_value=0)

a    22.0
b    20.0
c    52.0
d    32.0
dtype: float64

In [104]:
names = ['alice', 'bob', 'charle']

bananas = pd.Series([10, 3, 9], index=names)
oranges = pd.Series([3, 11, 6], index=names)

fruits_jan = pd.DataFrame({'bananas': bananas, 'oranges': oranges})

In [105]:
bananas = pd.Series([6, 1], index=names[:-1])
apples = pd.Series([8, 5], index=names[1:])

fruits_feb = pd.DataFrame({'bananas': bananas, 'apples': apples})

In [106]:
fruits_jan

        bananas  oranges
alice        10        3
bob           3       11
charle        9        6

In [107]:
fruits_feb

        bananas  apples
alice       6.0     NaN
bob         1.0     8.0
charle      NaN     5.0

In [108]:
eaten_fruits = fruits_jan + fruits_feb
eaten_fruits

        apples  bananas  oranges
alice      NaN     16.0      NaN
bob        NaN      4.0      NaN
charle     NaN      NaN      NaN

- Lorsqu’une valeur est absente dans toutes les DataFrame, NaN est conservé.

In [109]:
eaten_fruits = fruits_jan.add(fruits_feb, fill_value=0)
eaten_fruits

        apples  bananas  oranges
alice      NaN     16.0      3.0
bob        8.0      4.0     11.0
charle     5.0      9.0      6.0

In [110]:
eaten_fruits.fillna(0)

        apples  bananas  oranges
alice      0.0     16.0      3.0
bob        8.0      4.0     11.0
charle     5.0      9.0      6.0

In [111]:
eaten_fruits.dropna()

        apples  bananas  oranges
bob        8.0      4.0     11.0
charle     5.0      9.0      6.0

In [112]:
eaten_fruits

        apples  bananas  oranges
alice      NaN     16.0      3.0
bob        8.0      4.0     11.0
charle     5.0      9.0      6.0

In [113]:
data_frame = pd.DataFrame(
    np.random.randint(1, 10, size=(3, 3)),
    columns=list('abc'),
    index=list('xyz')
)

data_frame

   a  b  c
x  3  9  2
y  3  7  1
z  1  6  6

In [114]:
series_row = pd.Series(
    [100, 200, 300],
    index=list('abc')
)

series_row

a    100
b    200
c    300
dtype: int64

In [115]:
series_col = pd.Series(
    [400, 500, 600],
    index=list('xyz')
)

series_col

x    400
y    500
z    600
dtype: int64

In [116]:
data_frame + series_row

     a    b    c
x  103  209  302
y  103  207  301
z  101  206  306

In [117]:
data_frame + series_col

    a   b   c   x   y   z
x NaN NaN NaN NaN NaN NaN
y NaN NaN NaN NaN NaN NaN
z NaN NaN NaN NaN NaN NaN

In [118]:
data_frame.add(series_col, axis=0)

     a    b    c
x  403  409  402
y  503  507  501
z  601  606  606

## Opérations sur les chaînes de caractères

In [119]:
names = ['alice', ' bOB', 'Marc', 'bill', 3, ' JULIE ', np.nan]
age = pd.Series(names)

print(age)

0      alice
1        bOB
2       Marc
3       bill
4          3
5     JULIE
6        NaN
dtype: object

- Nettoyage de données

In [120]:
a = age.str.lower()
a = a.str.strip()
a

0    alice
1      bob
2     marc
3     bill
4      NaN
5    julie
6      NaN
dtype: object

In [121]:
[x for x in age.str.lower().str.strip()]

['alice', 'bob', 'marc', 'bill', nan, 'julie', nan]

In [122]:
print(a)

0    alice
1      bob
2     marc
3     bill
4      NaN
5    julie
6      NaN
dtype: object

In [123]:
print(a.str[-1])

0      e
1      b
2      c
3      l
4    NaN
5      e
6    NaN
dtype: object

## La gestion des `NaN` et `None`

In [124]:
s = pd.Series([1, 2])
s

0    1
1    2
dtype: int64

In [125]:
s[0] = np.nan
s

0    NaN
1    2.0
dtype: float64

In [126]:
s = pd.Series([1, 2])
s

0    1
1    2
dtype: int64

In [127]:
s[0] = None
s

0    NaN
1    2.0
dtype: float64

In [128]:
s.isna()

0     True
1    False
dtype: bool

In [129]:
s.isnull()

0     True
1    False
dtype: bool

In [130]:
s.notna()

0    False
1     True
dtype: bool

In [131]:
s.notnull()

0    False
1     True
dtype: bool

In [132]:
s.dropna()

1    2.0
dtype: float64

In [133]:
s.fillna(0)

0    0.0
1    2.0
dtype: float64

In [134]:
names = ['alice', 'bob', 'charles']

bananas = pd.Series([6, 1], index=names[:-1])
apples = pd.Series([8, 5], index=names[1:])

fruits_feb = pd.DataFrame({'bananas': bananas, 'apples': apples})

print(fruits_feb)

         bananas  apples
alice        6.0     NaN
bob          1.0     8.0
charles      NaN     5.0

In [135]:
fruits_feb.isna()

         bananas  apples
alice      False    True
bob        False   False
charles     True   False

In [136]:
fruits_feb.notna()

         bananas  apples
alice       True   False
bob         True    True
charles    False    True

In [137]:
p = pd.DataFrame([
    [1, 2, np.nan], 
    [3, np.nan, np.nan], 
    [7, 5, np.nan]
])

p

   0    1   2
0  1  2.0 NaN
1  3  NaN NaN
2  7  5.0 NaN

In [138]:
p.dropna()

Empty DataFrame
Columns: [0, 1, 2]
Index: []

In [139]:
p.dropna(axis=1)

   0
0  1
1  3
2  7

In [140]:
p.dropna(axis=1, how='all')

   0    1
0  1  2.0
1  3  NaN
2  7  5.0

In [141]:
p.dropna(thresh=2)

   0    1   2
0  1  2.0 NaN
2  7  5.0 NaN

In [142]:
print(p)

   0    1   2
0  1  2.0 NaN
1  3  NaN NaN
2  7  5.0 NaN

In [143]:
p.fillna(-1)

   0    1    2
0  1  2.0 -1.0
1  3 -1.0 -1.0
2  7  5.0 -1.0

In [145]:
p.fillna('bfill')

   0      1      2
0  1    2.0  bfill
1  3  bfill  bfill
2  7    5.0  bfill

In [147]:
p.fillna('ffill', axis=1)

     0      1      2
0  1.0    2.0  ffill
1  3.0  ffill  ffill
2  7.0    5.0  ffill

In [148]:
!p.dropna?

In [149]:
!p.fillna?

## Les MultiIndex

`pandas` avait historiquement d'autres structures de données en plus des `Series` et des `DataFrame` permettant d'exprimer des dimensionnalités supérieures à 2, comme par exemple les `Panel`. Mais pour des raisons de maintenance du code et d'optimisation, les développeurs ont décidé de ne garder que les `Series` et les `DataFrame`. Alors, comment exprimer des données avec plus de deux dimensions ?

On utilise pour cela des `MultiIndex`. Un `MultiIndex` est un index qui peut être utilisé partout où l'on utilise un index (dans une `Series`, ou comme ligne ou colonne d'une `DataFrame`) et qui a pour caractéristique d'avoir plusieurs niveaux.

Comme tous types d'index, et parce qu'un `MultiIndex` est une sous classe d'`Index`, pandas va correctement aligner les `Series` et les `DataFrame` avec des `MultiIndex`.

In [150]:
names = ['alice', 'bob', 'sonia']

age = pd.Series([12, 13, 16], index=names)
height = pd.Series([130, 140, 165], index=names)
sex = pd.Series(list('fmf'), index=names)

p = pd.DataFrame({'age': age, 'height': height, 'sex': sex})
print(p)

       age  height sex
alice   12     130   f
bob     13     140   m
sonia   16     165   f

- Passage d'une DataFrame à une Séries avec un MultiIndex

In [151]:
s_multiIndex = p.unstack()
print(s_multiIndex)

age     alice     12
        bob       13
        sonia     16
height  alice    130
        bob      140
        sonia    165
sex     alice      f
        bob        m
        sonia      f
dtype: object

In [152]:
s_multiIndex.index

MultiIndex([(   'age', 'alice'),
            (   'age',   'bob'),
            (   'age', 'sonia'),
            ('height', 'alice'),
            ('height',   'bob'),
            ('height', 'sonia'),
            (   'sex', 'alice'),
            (   'sex',   'bob'),
            (   'sex', 'sonia')],
           )

In [153]:
print(s_multiIndex.values)

[12 13 16 130 140 165 'f' 'm' 'f']

In [154]:
print(s_multiIndex.keys())

MultiIndex([(   'age', 'alice'),
            (   'age',   'bob'),
            (   'age', 'sonia'),
            ('height', 'alice'),
            ('height',   'bob'),
            ('height', 'sonia'),
            (   'sex', 'alice'),
            (   'sex',   'bob'),
            (   'sex', 'sonia')],
           )

### Créer un MultiIndex

In [155]:
names = ['alice', 'alice', 'alice', 'bob', 'bob', 'bob']
age = [2014, 2015, 2016, 2014, 2015, 2016]

s_list = pd.Series(
    [40, 42, 45, 38, 40, 40],
    index=[names, age]
)

print(s_list)

alice  2014    40
       2015    42
       2016    45
bob    2014    38
       2015    40
       2016    40
dtype: int64

- Ou

In [156]:
s_tuple = pd.Series({
    ('alice', 2014): 40,
    ('alice', 2015): 42,
    ('alice', 2016): 45,
    ('bob', 2014): 38,
    ('bob', 2015): 40,
    ('bob', 2016): 40
})

print(s_tuple)

alice  2014    40
       2015    42
       2016    45
bob    2014    38
       2015    40
       2016    40
dtype: int64

- avec `from_product()`

In [157]:
name = ['alice', 'bob']
year = [2014, 2015, 2016]

i = pd.MultiIndex.from_product([name, year])
s = pd.Series([40, 42, 45, 38, 40,40], index=i)

print(s)

alice  2014    40
       2015    42
       2016    45
bob    2014    38
       2015    40
       2016    40
dtype: int64

- Nommer les niveaux d'un MultiIndex

In [158]:
name = ['alice', 'bob']
year = [2014, 2015, 2016]

i = pd.MultiIndex.from_product([name, year], names=['name', 'year'])
s = pd.Series([40, 42, 45, 38, 40,40], index=i)

print(s)

name   year
alice  2014    40
       2015    42
       2016    45
bob    2014    38
       2015    40
       2016    40
dtype: int64

In [159]:
s.index.names = ['NAMES', 'YEARS']
print(s)

NAMES  YEARS
alice  2014     40
       2015     42
       2016     45
bob    2014     38
       2015     40
       2016     40
dtype: int64

In [160]:
index = pd.MultiIndex.from_product([[2013, 2014],
                                    [1, 2, 3]],
                                   names=['year',
                                          'visit'])

columns = pd.MultiIndex.from_product([['Bob', 'Sue'],
                                      ['avant', 'arrière']],
                                     names=['client',
                                            'pression'])

# on crée des pressions de pneus factices
data = 2 + np.random.rand(6, 4)

# on crée la DataFrame
mecanics_data = pd.DataFrame(data, index=index, columns=columns)
print(mecanics_data)

client           Bob                 Sue
pression       avant   arrière     avant   arrière
year visit
2013 1      2.212264  2.373214  2.866606  2.058504
     2      2.882356  2.827505  2.004482  2.324628
     3      2.694812  2.666670  2.978603  2.806478
2014 1      2.675406  2.344078  2.874113  2.821748
     2      2.266248  2.489805  2.866020  2.218501
     3      2.160624  2.367515  2.094876  2.335094

In [161]:
mecanics_data.loc[2013, 'Bob']

pression     avant   arrière
visit
1         2.212264  2.373214
2         2.882356  2.827505
3         2.694812  2.666670

In [162]:
mecanics_data.loc[(2013, 2), ('Bob', 'avant')]

np.float64(2.8823559725488006)

In [163]:
# slice(None) signifie tous les éléments du niveau
print(mecanics_data.loc[slice((2013, 2), (2014, 1)), ('Sue', slice(None))])

client           Sue
pression       avant   arrière
year visit
2013 2      2.004482  2.324628
     3      2.978603  2.806478
2014 1      2.874113  2.821748

In [164]:
# on peut utiliser la notation : si on ne distingue par les niveaux
print(mecanics_data.loc[(slice(None), slice(1, 2)), :])

client           Bob                 Sue
pression       avant   arrière     avant   arrière
year visit
2013 1      2.212264  2.373214  2.866606  2.058504
     2      2.882356  2.827505  2.004482  2.324628
2014 1      2.675406  2.344078  2.874113  2.821748
     2      2.266248  2.489805  2.866020  2.218501

In [165]:
# on peut aussi utiliser pd.IndexSlice pour slicer avec une notation
# un peu plus concise
idx = pd.IndexSlice
print(idx, '\n')
print(mecanics_data.loc[idx[:, 1:2], idx['Sue', :]])

<pandas.core.indexing._IndexSlice object at 0x12331c1a0>

client           Sue
pression       avant   arrière
year visit
2013 1      2.866606  2.058504
     2      2.004482  2.324628
2014 1      2.874113  2.821748
     2      2.866020  2.218501

In [166]:
idx