In [2]:
import numpy as np
import pandas as pd

In [3]:
prenoms = ['liz', 'bob', 'bill', 'eve']

In [4]:
age = pd.Series([25, 30, 35, 40], index=prenoms)

In [5]:
taille = pd.Series([160, 175, 170, 180], index=prenoms)

In [6]:
sexe = pd.Series(list("fhhf"), index=prenoms)

In [7]:
df = pd.DataFrame(
    {
        'age': age,
        'taille': taille,
        'sexe': sexe
    },
)

In [8]:
df

      age  taille sexe
liz    25     160    f
bob    30     175    h
bill   35     170    h
eve    40     180    f

In [9]:
df.index

Index(['liz', 'bob', 'bill', 'eve'], dtype='object')

In [10]:
df.columns

Index(['age', 'taille', 'sexe'], dtype='object')

In [11]:
df.values

array([[25, 160, 'f'],
       [30, 175, 'h'],
       [35, 170, 'h'],
       [40, 180, 'f']], dtype=object)

In [12]:
df.head(2)

     age  taille sexe
liz   25     160    f
bob   30     175    h

In [13]:
df.tail(2)

      age  taille sexe
bill   35     170    h
eve    40     180    f

In [14]:
df.describe()

             age      taille
count   4.000000    4.000000
mean   32.500000  171.250000
std     6.454972    8.539126
min    25.000000  160.000000
25%    28.750000  167.500000
50%    32.500000  172.500000
75%    36.250000  176.250000
max    40.000000  180.000000

### Indexation de ligne

In [15]:
df.loc['liz']

age        25
taille    160
sexe        f
Name: liz, dtype: object

### Indexation de cellule ou d'observation

In [16]:
print(df.loc['liz', 'age'])

25

### Indexation d'un sous ensemble de DataFrame

In [21]:
df.loc[:, 'taille']

0    160
1    175
2    170
3    180
Name: taille, dtype: int64

### Application d'un masque et broadcasting

In [22]:
df.loc[df.loc[:, 'age']<32]

  prenom  age  taille sexe
0    liz   25     160    f
1    bob   30     175    h

### Transformation d'un index ligne en index de colonne

In [19]:
df = df.reset_index()
df

  index  age  taille sexe
0   liz   25     160    f
1   bob   30     175    h
2  bill   35     170    h
3   eve   40     180    f

### Renommer des index de colonne

In [20]:
df = df.rename(columns={'index': 'prenom'})
df

  prenom  age  taille sexe
0    liz   25     160    f
1    bob   30     175    h
2   bill   35     170    h
3    eve   40     180    f

### Redéfinir un index de colonne en tant qu'index de ligne

In [27]:
df = df.set_index('age')
df

    prenom  taille sexe
age
25     liz     160    f
30     bob     175    h
35    bill     170    h
40     eve     180    f

## Approche moderne

In [23]:
df = pd.DataFrame(
    {
        'age': age,
        'taille': taille,
        'sexe': sexe
    },
)

In [24]:
df

      age  taille sexe
liz    25     160    f
bob    30     175    h
bill   35     170    h
eve    40     180    f

In [25]:
df = (
    df.reset_index()
    .rename(columns={'index':'prenoms'})
    .set_index('age')
)

In [26]:
df

    prenoms  taille sexe
age
25      liz     160    f
30      bob     175    h
35     bill     170    h
40      eve     180    f

In [34]:
df1 = pd.DataFrame(np.ones((2, 2), dtype=np.int8),
                   index=list('ab'),
                   columns=list('xy')
                   )

In [35]:
df1

   x  y
a  1  1
b  1  1

In [36]:
df2 = pd.DataFrame(np.ones((2, 2), dtype=np.int8),
                   index=list('ac'),
                   columns=list('xz')
                   )

In [37]:
df2

   x  z
a  1  1
c  1  1

### Résolution d'alignement d'index

In [38]:
df1 + df2

     x   y   z
a  2.0 NaN NaN
b  NaN NaN NaN
c  NaN NaN NaN

- `fill_value` ne fonctionne que s'il manque une valeur à gauche ou à droite (pas si les deux sont absents)

In [39]:
df1.add(df2, fill_value=0)

     x    y    z
a  2.0  1.0  1.0
b  1.0  1.0  NaN
c  1.0  NaN  1.0

In [40]:
df = df1.add(df2, fill_value=0)
df

     x    y    z
a  2.0  1.0  1.0
b  1.0  1.0  NaN
c  1.0  NaN  1.0

- Remplacer les valeur `NaN` par une autre valeur

In [41]:
df.fillna(-1)

     x    y    z
a  2.0  1.0  1.0
b  1.0  1.0 -1.0
c  1.0 -1.0  1.0

- Retirer les lignes contenant des valeurs `NaN`

In [42]:
df.dropna()

     x    y    z
a  2.0  1.0  1.0