In [1]:
import pandas as pd
import numpy as np

Pandas est une librairie qui permet de manipuler les labels(index) d'un ensemble de données avec des structrures données:
- Series (Pour les structures à 1 dimension)
- DataFrame (Pour les structures à 2 dimensions

Pandas supporte de grande variété de format de données à l'importation et à l'exportation tels que: CSV, SQL, Json, Excel, Html, Python, ...

## Création d'une Series avec `np.Series()`

Une `Series` a une certaine similarité avec un dictionnaire python

In [2]:
S = pd.Series([x**2 for x in range(10)])
S

0     0
1     1
2     4
3     9
4    16
5    25
6    36
7    49
8    64
9    81
dtype: int64

In [3]:
S = pd.Series([x**2 for x in range(10)], dtype='int8')
S

0     0
1     1
2     4
3     9
4    16
5    25
6    36
7    49
8    64
9    81
dtype: int8

In [4]:
S = pd.Series(data=[x**2 for x in range(10)],
              index=[x for x in 'abcdefghij'],
              dtype='int8')
S

a     0
b     1
c     4
d     9
e    16
f    25
g    36
h    49
i    64
j    81
dtype: int8

- Avec un dictionnaire

In [5]:
d = {k: v**2 for k, v in zip('abcdefghij', range(10))}
print(d)

{'a': 0, 'b': 1, 'c': 4, 'd': 9, 'e': 16, 'f': 25, 'g': 36, 'h': 49, 'i': 64, 'j': 81}

In [6]:
S = pd.Series(d, dtype='int8')
S

a     0
b     1
c     4
d     9
e    16
f    25
g    36
h    49
i    64
j    81
dtype: int8

In [7]:
print(S['f'])

25

In [8]:
print(S.loc['f'])

25

L’index d’une Series est un objet implémenté sous la forme d’un ndarray de numpy, mais qui ne peut contenir que des objets hashables (pour garantir la performance de l’accès).

In [9]:
print(S.index)

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], dtype='str')

Les valeurs d'une Series sont accessibles avec l'attribut `values`qui renvoie un objet ndarray

In [10]:
print(S.values)

[ 0  1  4  9 16 25 36 49 64 81]

Mais une Series a également une interface de dictionnaire à laquelle on accède de la manière suivante:

In [11]:
S.keys()

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], dtype='str')

In [67]:
S.items()

In [12]:
for k, v in S.items():
    print(k, v)

a 0
b 1
c 4
d 9
e 16
f 25
g 36
h 49
i 64
j 81

Le test d'appartenance est possible sur les index

In [13]:
'a' in S, 'z' in S

(True, False)

Il est possible de modifier ou d'avoir des données de différents types dans un dataframe.

In [14]:
S = pd.Series(range(10_000))
S

0          0
1          1
2          2
3          3
4          4
        ...
9995    9995
9996    9996
9997    9997
9998    9998
9999    9999
Length: 10000, dtype: int64

In [15]:
S.values.dtype

dtype('int64')

In [16]:
%timeit S**2

57.2 μs ± 1.41 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

In [18]:
S[10_000] = 'spam'
S

0           0
1           1
2           2
3           3
4           4
         ...
9996     9996
9997     9997
9998     9998
9999     9999
10000    spam
Length: 10001, dtype: object

In [19]:
del S[10_000]

In [20]:
S

0          0
1          1
2          2
3          3
4          4
        ...
9995    9995
9996    9996
9997    9997
9998    9998
9999    9999
Length: 10000, dtype: object

In [21]:
%timeit S**2

439 μs ± 8.48 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [22]:
S.values.dtype

dtype('O')

In [23]:
print(S.values.dtype)

object

Maintenant, les opérations vectorisées le sont sur des objets Python et non plus sur des int64, il y a donc un impact sur la performance.

In [24]:
S = pd.Series([1, 2, 3])
S

0    1
1    2
2    3
dtype: int64

In [25]:
S[3] = '4'
S

0    1
1    2
2    3
3    4
dtype: object

Les entiers sont additionnés, mais les chaînes de caractères concaténées.

In [26]:
S + S

0     2
1     4
2     6
3    44
dtype: object

- Avec des index de type `str`

In [27]:
s = pd.Series([20, 30, 40, 50],
              index=['eve', 'bill', 'liz', 'bob'])

In [28]:
s

eve     20
bill    30
liz     40
bob     50
dtype: int64

Accéder aux valeurs d'une Series

In [29]:
s.values

array([20, 30, 40, 50])

Accéder aux index d'une Series

In [30]:
s.index

Index(['eve', 'bill', 'liz', 'bob'], dtype='str')

Cette notation `s['eve']` doit être évité à cause des effets de bords

In [31]:
s.loc['eve']

np.int64(20)

Le slicing sur les `series` inclut les 2 éléments de l'intervalle

In [32]:
s.loc['eve': 'liz']

eve     20
bill    30
liz     40
dtype: int64

In [33]:
s = pd.Series([20, 30, 40, 50],
              index=['eve', 'liz', 'bill', 'bob'])

In [34]:
s.loc['eve': 'liz']

eve    20
liz    30
dtype: int64

Le slicing sur les labels ne fonctionne pas s'ils sont dubliqués et ne sont pas triés

In [35]:
animaux = ['chien', 'chat', 'chat', 'chien', 'poisson']
proprio = ['eve', 'bob', 'eve', 'bill', 'liz']

In [36]:
s = pd.Series(animaux, index=proprio)
s

eve       chien
bob        chat
eve        chat
bill      chien
liz     poisson
dtype: str

In [37]:
# Ceci lancera une erreur
# s.loc['eve': 'liz']

In [38]:
s = s.sort_index()
s

bill      chien
bob        chat
eve       chien
eve        chat
liz     poisson
dtype: str

In [39]:
s.loc['eve': 'liz']

eve      chien
eve       chat
liz    poisson
dtype: str

In [40]:
s.iloc[0]

'chien'

In [41]:
s.iloc[4]

'poisson'

In [42]:
s.iloc[1:3]

bob     chat
eve    chien
dtype: str

In [43]:
s=='chien'

bill     True
bob     False
eve      True
eve     False
liz     False
dtype: bool

In [44]:
s.loc[(s=='chien')]

bill    chien
eve     chien
dtype: str

In [45]:
s.loc[(s=='chien') | (s=='poisson')]

bill      chien
eve       chien
liz     poisson
dtype: str

In [46]:
s.loc[~((s=='chien') | (s=='poisson'))] = 'autre'
s

bill      chien
bob       autre
eve       chien
eve       autre
liz     poisson
dtype: str

In [47]:
s1 = pd.Series([1, 2, 3], index=list('abc'))

In [48]:
s2 = pd.Series([5, 6, 7], index=list('acd'))

In [49]:
s1

a    1
b    2
c    3
dtype: int64

In [50]:
s2

a    5
c    6
d    7
dtype: int64

L'opération n'est défini que pour les entités ayant le même label

In [51]:
s1 + s2

a    6.0
b    NaN
c    9.0
d    NaN
dtype: float64

In [52]:
s1.add(s2)

a    6.0
b    NaN
c    9.0
d    NaN
dtype: float64

In [53]:
s1.add(s2, fill_value=50)

a     6.0
b    52.0
c     9.0
d    57.0
dtype: float64

In [68]:
argent_poche_janvier = pd.Series([30, 35, 20],
                                 index=['alice', 'bob', 'julie'])
argent_poche_février = pd.Series([30, 35, 20],
                                 index=['alice', 'julie', 'sonia'])
argent_poche_janvier + argent_poche_février

alice    60.0
bob       NaN
julie    55.0
sonia     NaN
dtype: float64

In [69]:
argent_poche_janvier.add(argent_poche_février, fill_value=0)

alice    60.0
bob      35.0
julie    55.0
sonia    20.0
dtype: float64

In [70]:
s = pd.Series([30, 35, 20], index=['alice', 'bob', 'julie'])
s

alice    30
bob      35
julie    20
dtype: int64

In [71]:
print(s[s>25])

alice    30
bob      35
dtype: int64

In [72]:
print(s[['alice', 'julie']])

alice    30
julie    20
dtype: int64

In [74]:
s[s<=25] = np.nan
s

alice    30.0
bob      35.0
julie     NaN
dtype: float64

In [75]:
s = s + 10
s

alice    40.0
bob      45.0
julie     NaN
dtype: float64

In [83]:
s = pd.Series([30, 35, 20, 28], index=['alice', 'bob', 'julie', 'sonia'])
s

alice    30
bob      35
julie    20
sonia    28
dtype: int64

In [84]:
print(s['alice'])

30

In [89]:
s['alice':'julie']

alice    30
bob      35
julie    20
dtype: int64

In [90]:
s[0:2]

alice    30
bob      35
dtype: int64

In [92]:
# Regardons le slice sur un index avec un ordre particulier
s = pd.Series([30, 35, 20, 28], index=['alice', 'bob', 'julie', 'sonia'])
print(s['alice':'julie'])

alice    30
bob      35
julie    20
dtype: int64

In [93]:
# Si on change l'ordre de l'index, ça change la signification du slice
s = pd.Series([30, 35, 20, 28], index=['alice', 'bob', 'sonia', 'julie'])
print(s['alice':'julie'])

alice    30
bob      35
sonia    20
julie    28
dtype: int64

In [94]:
# mon index a des labels dupliqués, mais a une croissance monotonique
s = pd.Series([30, 35, 20, 12], index=['a', 'a', 'b', 'c'])
# le slice est défini
s['a': 'b']

a    30
a    35
b    20
dtype: int64

In [95]:
# mon index a des labels dupliqués et n'a pas de croissance monotonique
s = pd.Series([30, 35, 20, 12], index=['a', 'b', 'c', 'a'])
# le slice n'est plus défini
try:
    s['a': 'b']
except KeyError as e:
    print(f"Je n'arrive pas à extraire un slice :\n{e}")

Je n'arrive pas à extraire un slice :
"Cannot get left slice bound for non-unique label: 'a'"

In [96]:
s = pd.Series(['a', 'b', 'c'], index=[2, 0, 1])
print(f"Si on accède directement à un élément, priorité au label : {s[0]}")
print(f"Si on calcule un slice, priorité à la position : {s[0:1]}")

Si on accède directement à un élément, priorité au label : b
Si on calcule un slice, priorité à la position : 2    a
dtype: str

## `df.loc()` vs `df.iloc()`

In [98]:
s = pd.Series([1000, 2000, 3000, 4000], index=['deux', 'zero', 'un', 'quatre'])
print(s)

deux      1000
zero      2000
un        3000
quatre    4000
dtype: int64

In [99]:
# accès au label
print(s.loc['zero'])

2000

In [100]:
# accès à la position
print(s.iloc[0])

1000

In [101]:
print(s.loc['deux':'zero'])

deux    1000
zero    2000
dtype: int64

In [102]:
print(s.iloc[1:3])

zero    2000
un      3000
dtype: int64

## Exemple de manipulation possible sur un DataFrame

In [54]:
# Seaborn est un module pour dessiner des courbes qui améliore sensiblement matplotlib.
# Seaborn vient avec quelques jeux de données sur lesquels on peut jouer.
import seaborn as sns

# chargeons un jeu de données qui représente des pourboires
tips = sns.load_dataset('tips')

In [56]:
type(tips)

pandas.DataFrame

In [55]:
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [57]:
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [58]:
tips.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [63]:
tips.groupby('sex', observed=True).mean(numeric_only=True)

        total_bill       tip      size
sex
Male     20.744076  3.089618  2.630573
Female   18.056897  2.833448  2.459770

In [64]:
tips.groupby('day', observed=True).mean(numeric_only=True)

      total_bill       tip      size
day
Thur   17.682742  2.771452  2.451613
Fri    17.151579  2.734737  2.105263
Sat    20.441379  2.993103  2.517241
Sun    21.410000  3.255132  2.842105

In [65]:
tips.groupby('time', observed=True).mean(numeric_only=True)

        total_bill       tip      size
time
Lunch    17.168676  2.728088  2.411765
Dinner   20.797159  3.102670  2.630682