In [1]:
import numpy as np
import pandas as pd
from pandas.conftest import axis

In [2]:
df1 = pd.DataFrame(np.random.randint(1, 10, size=(2, 2)),
    index=list('xy'),
    columns=list('ab')
)

df1

   a  b
x  4  1
y  7  9

In [3]:
df2 = pd.DataFrame(np.random.randint(1, 10, size=(2, 2)),
    index=list('zt'),
    columns=list('ab')
)

df2

   a  b
z  1  4
t  7  3

## Concaténer des DataFrames avec `pd.concat()`

In [4]:
pd.concat([df1, df2])

   a  b
x  4  1
y  7  9
z  1  4
t  7  3

### Changer le sens de la concaténation pour une orientation horizontale

In [7]:
df1 = pd.DataFrame(np.random.randint(1, 10, size=(2, 2)),
    index=list('xy'),
    columns=list('ab')
)

df1

   a  b
x  3  1
y  4  6

In [8]:
df2 = pd.DataFrame(np.random.randint(1, 10, size=(2, 2)),
    index=list('xy'),
    columns=list('cd')
)

df2

   c  d
x  3  1
y  5  7

In [10]:
pd.concat([df1, df2], axis=1)

   a  b  c  d
x  3  1  3  1
y  4  6  5  7

## Jointure des DataFrames avec `pd.merge()`

In [12]:
df1 = pd.DataFrame({'personnel': ['Bob', 'Lisa', 'Sue'],
                    'groupe': ['SAF', 'R&D', 'RH']})

df1

  personnel groupe
0       Bob    SAF
1      Lisa    R&D
2       Sue     RH

In [13]:
df2 = pd.DataFrame({'personnel': ['Lisa', 'Bob', 'Sue'],
                    'date embauche': ['2004', '2008', '2014']})

df2

  personnel date embauche
0      Lisa          2004
1       Bob          2008
2       Sue          2014

In [14]:
pd.merge(df1, df2)

  personnel groupe date embauche
0       Bob    SAF          2008
1      Lisa    R&D          2004
2       Sue     RH          2014

## Regrouper des DataFrames avec `pd.groupby()`

In [15]:
import seaborn as sns

In [17]:
titanic = sns.load_dataset('titanic').loc[:, ['survived', 'sex', 'class']]

titanic.head(10)

   survived     sex   class
0         0    male   Third
1         1  female   First
2         1  female   Third
3         1  female   First
4         0    male   Third
5         0    male   Third
6         0    male   First
7         0    male   Third
8         1  female   Third
9         1  female  Second

In [18]:
titanic.shape

(891, 3)

In [19]:
titanic.loc[:, 'survived'].mean()

np.float64(0.3838383838383838)

In [20]:
titanic.loc[titanic.loc[:, 'class']=='First','survived'].mean()

np.float64(0.6296296296296297)

In [29]:
titanic.groupby('class')

In [32]:
g = titanic.groupby(['class', 'sex']).mean()

g

               survived
class  sex
First  female  0.968085
       male    0.368852
Second female  0.921053
       male    0.157407
Third  female  0.500000
       male    0.135447

In [33]:
g.index

MultiIndex([( 'First', 'female'),
            ( 'First',   'male'),
            ('Second', 'female'),
            ('Second',   'male'),
            ( 'Third', 'female'),
            ( 'Third',   'male')],
           names=['class', 'sex'])

## Faire pivoter un DataFrame avec ``

In [41]:
titanic.pivot_table('survived',
                    aggfunc=np.mean,
                    index='class',
                    columns='sex')

sex       female      male
class
First   0.968085  0.368852
Second  0.921053  0.157407
Third   0.500000  0.135447