In [58]:
import numpy as np
import pandas as pd

In [59]:
df1 = pd.DataFrame(np.random.randint(1, 10, size=(2, 2)),
    index=list('xy'),
    columns=list('ab')
)

df1

   a  b
x  8  5
y  3  8

In [60]:
df2 = pd.DataFrame(np.random.randint(1, 10, size=(2, 2)),
    index=list('zt'),
    columns=list('ab')
)

df2

   a  b
z  8  7
t  2  5

## Concaténer des DataFrames avec `pd.concat()`

In [61]:
pd.concat([df1, df2])

   a  b
x  8  5
y  3  8
z  8  7
t  2  5

In [62]:
s1 = pd.Series([30, 35], index=['alice', 'bob'])
s2 = pd.Series([32, 22, 29], index=['bill', 'alice', 'jo'])

In [63]:
s1

alice    30
bob      35
dtype: int64

In [64]:
s2

bill     32
alice    22
jo       29
dtype: int64

In [65]:
try:
    pd.concat([s1, s2], verify_integrity=True)
except ValueError as e:
    print(f"Erreur de concaténation:\n{e}")

Erreur de concaténation:
Indexes have overlapping values: Index(['alice'], dtype='str')

In [66]:
s1 = pd.Series(range(1000), index=[chr(x) for x in  range(1000)])
s1.tail()

ϣ    995
Ϥ    996
ϥ    997
Ϧ    998
ϧ    999
dtype: int64

In [67]:
s2 = pd.Series(range(1000), index=[chr(x+2000) for x in range(1000)])
s2.tail()

ள    995
ழ    996
வ    997
ஶ    998
ஷ    999
dtype: int64

In [68]:
%timeit pd.concat([s1, s2], verify_integrity=True)

227 μs ± 15.2 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [69]:
%timeit pd.concat([s1, s2])

126 μs ± 439 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

### Changer le sens de la concaténation pour une orientation horizontale

In [70]:
df1 = pd.DataFrame(np.random.randint(1, 10, size=(2, 2)),
    index=list('xy'),
    columns=list('ab')
)

df1

   a  b
x  7  8
y  1  2

In [71]:
df2 = pd.DataFrame(np.random.randint(1, 10, size=(2, 2)),
    index=list('xy'),
    columns=list('cd')
)

df2

   c  d
x  8  7
y  3  7

In [72]:
pd.concat([df1, df2], axis=1)

   a  b  c  d
x  7  8  8  7
y  1  2  3  7

In [73]:
pd.concat([df1, df2])

     a    b    c    d
x  7.0  8.0  NaN  NaN
y  1.0  2.0  NaN  NaN
x  NaN  NaN  8.0  7.0
y  NaN  NaN  3.0  7.0

In [74]:
pd.concat([df1, df2], join='inner')

Empty DataFrame
Columns: []
Index: [x, y, x, y]

In [75]:
pd.concat([df1, df2], axis=1).reindex(['x'])

   a  b  c  d
x  7  8  8  7

In [76]:
pd.concat([df1, df2], axis=1).reindex(['y'])

   a  b  c  d
y  1  2  3  7

In [77]:
pd.concat([df1, df2], axis=1).reindex(df2.columns, axis=1)

   c  d
x  8  7
y  3  7

In [78]:
pd.concat([df1, df2], axis=1).reindex(['a', 'b'], axis=1)

   a  b
x  7  8
y  1  2

## Jointure des DataFrames avec `pd.merge()`

Par défaut, `merge` fait un **inner join**

In [79]:
df1 = pd.DataFrame({'personnel': ['Bob', 'Lisa', 'Sue'],
                    'groupe': ['SAF', 'R&D', 'RH']})

df1

  personnel groupe
0       Bob    SAF
1      Lisa    R&D
2       Sue     RH

In [80]:
df2 = pd.DataFrame({'personnel': ['Lisa', 'Bob', 'Sue'],
                    'date embauche': ['2004', '2008', '2014']})

df2

  personnel date embauche
0      Lisa          2004
1       Bob          2008
2       Sue          2014

In [81]:
pd.merge(df1, df2)

  personnel groupe date embauche
0       Bob    SAF          2008
1      Lisa    R&D          2004
2       Sue     RH          2014


Il existe trois type de merges :

- one-to-one, c’est le merge lorqu’il n’y a pas de labels dupliqués dans les colonnes utilisées comme critère de merge ;

- many-to-one, c’est le merge lorsque l’une des deux colonnes contient des labels dupliqués, dans ce cas, on applique la stratégie one-to-one pour chaque label dupliqué, donc les entrées dupliquées sont préservées ;

- many-to-many, c’est la stratégie lorsqu’il y a des entrées dupliquées dans les deux colonnes. Dans ce cas, on fait un produit cartésien des lignes.

In [107]:
df1 = pd.DataFrame({'patient': ['Bob', 'Lisa', 'Sue'],
                    'repas': ['SS', 'SS', 'SSR']})
df1

  patient repas
0     Bob    SS
1    Lisa    SS
2     Sue   SSR

In [108]:
df2 = pd.DataFrame({'repas': ['SS', 'SSR'],
                    'explication': ['sans sel', 'sans sucre']})
df2

  repas explication
0    SS    sans sel
1   SSR  sans sucre

In [109]:
pd.merge(df1, df2)

  patient repas explication
0     Bob    SS    sans sel
1    Lisa    SS    sans sel
2     Sue   SSR  sans sucre

In [111]:
df1 = pd.DataFrame({'patient': ['Bob', 'Lisa', 'Sue'],
                    'repas': ['SS', 'SS', 'SSR']})

df1

  patient repas
0     Bob    SS
1    Lisa    SS
2     Sue   SSR

In [112]:
df2 = pd.DataFrame({'repas': ['SS', 'SS', 'SSR'],
                    'explication': ['sans sel', 'légumes', 'sans sucre']})

df2

  repas explication
0    SS    sans sel
1    SS     légumes
2   SSR  sans sucre

In [113]:
pd.merge(df1, df2)

  patient repas explication
0     Bob    SS    sans sel
1     Bob    SS     légumes
2    Lisa    SS    sans sel
3    Lisa    SS     légumes
4     Sue   SSR  sans sucre

In [114]:
df1 = pd.DataFrame({'employee': ['Bob', 'Lisa', 'Sue'],
                    'group': ['Accounting', 'Engineering', 'HR']})

df1

  employee        group
0      Bob   Accounting
1     Lisa  Engineering
2      Sue           HR

In [115]:
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Sue'],
                    'hire_date': [2004, 2008, 2014]})

df2

  employee  hire_date
0     Lisa       2004
1      Bob       2008
2      Sue       2014

In [116]:
pd.merge(df1, df2, on='employee')

  employee        group  hire_date
0      Bob   Accounting       2008
1     Lisa  Engineering       2004
2      Sue           HR       2014

In [117]:
df1 = pd.DataFrame({'employee': ['Bob', 'Lisa', 'Sue'],
                    'group': ['Accounting', 'Engineering', 'HR']})
df1

  employee        group
0      Bob   Accounting
1     Lisa  Engineering
2      Sue           HR

In [118]:
df2 = pd.DataFrame({'name': ['Lisa', 'Bob', 'Sue'],
                    'hire_date': [2004, 2008, 2014]})
df2

   name  hire_date
0  Lisa       2004
1   Bob       2008
2   Sue       2014

In [121]:
m = pd.merge(df1, df2, left_on='employee', right_on='name')
m

  employee        group  name  hire_date
0      Bob   Accounting   Bob       2008
1     Lisa  Engineering  Lisa       2004
2      Sue           HR   Sue       2014

### Supprimer une colonne

In [123]:
m.drop('name', axis=1)

  employee        group  hire_date
0      Bob   Accounting       2008
1     Lisa  Engineering       2004
2      Sue           HR       2014

### Merge externe, à gauche et à droite

In [127]:
df1 = pd.DataFrame({'name': ['Bob', 'Lisa', 'Sue'],
                    'pulse': [70, 63, 81]})
df1

   name  pulse
0   Bob     70
1  Lisa     63
2   Sue     81

In [128]:
df2 = pd.DataFrame({'name': ['Eric', 'Bob', 'Marc'],
                    'weight': [60, 100, 70]})
df2

   name  weight
0  Eric      60
1   Bob     100
2  Marc      70

In [126]:
pd.merge(df1, df2)

  name  pulse  weight
0  Bob     70     100

In [129]:
pd.merge(df1, df2, how='outer')

   name  pulse  weight
0   Bob   70.0   100.0
1  Eric    NaN    60.0
2  Lisa   63.0     NaN
3  Marc    NaN    70.0
4   Sue   81.0     NaN

In [130]:
pd.merge(df1, df2, how='left')

   name  pulse  weight
0   Bob     70   100.0
1  Lisa     63     NaN
2   Sue     81     NaN

In [131]:
pd.merge(df1, df2, how='right')

   name  pulse  weight
0  Eric    NaN      60
1   Bob   70.0     100
2  Marc    NaN      70

## Regrouper des DataFrames avec `pd.groupby()`

In [82]:
import seaborn as sns

In [83]:
titanic = sns.load_dataset('titanic').loc[:, ['survived', 'sex', 'class']]

titanic.head(10)

   survived     sex   class
0         0    male   Third
1         1  female   First
2         1  female   Third
3         1  female   First
4         0    male   Third
5         0    male   Third
6         0    male   First
7         0    male   Third
8         1  female   Third
9         1  female  Second

In [84]:
titanic.shape

(891, 3)

In [85]:
titanic.loc[:, 'survived'].mean()

np.float64(0.3838383838383838)

In [86]:
titanic.loc[titanic.loc[:, 'class']=='First','survived'].mean()

np.float64(0.6296296296296297)

In [87]:
titanic.groupby('class')

In [88]:
g = titanic.groupby(['class', 'sex']).mean()

g

               survived
class  sex
First  female  0.968085
       male    0.368852
Second female  0.921053
       male    0.157407
Third  female  0.500000
       male    0.135447

In [89]:
g.index

MultiIndex([( 'First', 'female'),
            ( 'First',   'male'),
            ('Second', 'female'),
            ('Second',   'male'),
            ( 'Third', 'female'),
            ( 'Third',   'male')],
           names=['class', 'sex'])

## Faire pivoter un DataFrame avec ``

In [90]:
titanic.pivot_table('survived',
                    aggfunc=np.mean,
                    index='class',
                    columns='sex')

sex       female      male
class
First   0.968085  0.368852
Second  0.921053  0.157407
Third   0.500000  0.135447